version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appliance_directory
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "80:8080"